services:
  backend:
    image: mysite-backend
    pull_policy: never
    container_name: mysite-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./mongodb/.env   # <-- add this line
    depends_on:
      - mongodb
    ports:
      - 8000:8000

  frontend:
    image: mysite-frontend
    pull_policy: never
    container_name: mysite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  mongodb:
    image: mongo:7.0.12
    container_name: mysite-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db 
    env_file:
        - ./mongodb/.env

  mongo-express:
   image: mongo-express:latest
   container_name: mysite-mongo-express
   ports:
    - 8081:8081
   env_file:
    - ./mongodb/.env
   depends_on:
    - mongodb


volumes:
  mongo-data: